### ISSUE TITLE
Pass post body to executeWebScript method

### ISSUE THREAD

**Issue by ssc2015** [Alfresco/alfresco-js-api#97]
I need to call a webscript and post JSON data in the post body. There does not seem to be a way to pass post body to executeWebScript API currently. Is there any other way to accomplish this?

**Comment by eromano** [comment]
Hi @ssc2015 you should try to change the file alfrescoWebScript.js where there is the method executeWebScript and substitute with this one:

```javascript

    executeWebScript(httpMethod, scriptPath, scriptArgs, contextRoot, servicePath, postBody) {
        contextRoot = contextRoot || 'alfresco';
        servicePath = servicePath || 'service';

        if (!httpMethod  || this.allowedMethod.indexOf(httpMethod) === -1) {
            throw 'method allowed value  GET, POST, PUT and DELETE';
        }

        if (!scriptPath) {
            throw 'Missing the required parameter scriptPath when calling executeWebScript';
        }

        var pathParams = {};
        var headerParams = {};
        var formParams = {};

        var authNames = ['basicAuth'];
        var contentTypes = ['application/json'];
        var accepts = ['application/json', 'text/html'];
        var returnType = {};

        return this.apiClient.callApi(
            '/' +  servicePath + '/' + scriptPath, httpMethod,
            pathParams, scriptArgs, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType ,  contextRoot
        );
```
in order to get the new builded version you can run the command ```npm run build``` and after you will have the new version of the api in the folder dist.

Let me know if it works I can add it to the next release if is ok 👍

**Comment by ssc2015** [comment]
Hi @eromano,

It worked fine! Thanks for the quick response.

Now I am trying to download a file from the repository using getFileContent API but it is not returning anything. Is there any API I can use to download a file and save to local file system?

**Comment by eromano** [comment]
HI @ssc2015 
seems that in the last version there is an error about this method, if you want you can use the branch dev-eromano-97 that contain the fix for this bug and the webscript post body addition.

This is an example how to use the getFileContent:
```javascript

var nodeId = '80a94ac8-3ece-47ad-864e-5d939424c47c';

this.alfrescoJsApi.core.nodesApi.getFileContent(nodeId).then(function(data) {
    fs.writeFile('./test/grass.jpg', data, function(err) {
        if (err) {
            console.log(err);
        }
        console.log('The file was saved!');
    });
}, function(error) {
    console.error(error);
});
```

If you are using a browser and not a node enviroment you could use as workaround :

```javascript
        window.open(this.urlFile);
```
Thanks for report the issue will be fixed in the next release and in the meantime you can use the branch tha I said you above.

**Comment by eromano** [comment]
@ssc2015 i these changes are also on develop branch now.

**Comment by ssc2015** [comment]
Thanks! I ended up using getContentUrl API to get the URL and download it using request module. Once the updated version is released, I will try to go back to getFileContent API.

On another note, the executeWebScript API was not parsing the response when the return type is html or plain text. I changed one line of code in the "deserialize" method of ApiClient.js at line # 304:

**from**
if (data == null) {

**to**

if (data == null || Object.keys(data).length === 0) {

Then it started working fine. I am not sure if this has any negative impact though! Please let me know your thoughts. If all is well, please consider including this fix also in the next release.

**Comment by eromano** [comment]
@ssc2015 It seems strange to me because there is an Angular 2 component that works with HTML and JSON: 
https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-alfresco-webscript
I'll add some tests and I'll let you know about it thanks.
